version: v3
teleport:
  data_dir: /var/lib/teleport
  join_params:
    token_name: /opt/teleport-join-token
    method: token
  proxy_server: test.teleport.giantswarm.io:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
