version: v3
teleport:
  data_dir: /var/lib/teleport
  join_params:
    token_name: /opt/teleport-join-token
    method: token
  proxy_server: test.teleport.giantswarm.io:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  commands:
  - name: node
    command: [hostname]
    period: 1h0m0s
  - name: arch
    command: [uname, -p]
    period: 1h0m0s
  labels:
    mc: {{ .Values.managementCluster }}
    {{- $clusterName := include "resource.default.name" $ }}    
    {{ if ne .Values.managementCluster $clusterName }}
    wc: {{ include "resource.default.name" $ }}
    {{- end }}
    baseDomain: {{ .Values.baseDomain }}
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
