---
chart-repos:
  - cluster-catalog=https://giantswarm.github.io/cluster-catalog
  # We also add cluster-test-catalog, so we can more easily test dev builds of subcharts.
  # Charts from cluster-test-catalog should be used only for testing purposes.
  - cluster-test-catalog=https://giantswarm.github.io/cluster-test-catalog
