[plugins."io.containerd.grpc.v1.cri".registry]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
  {{- range $host, $config := .Values.connectivity.containerRegistries }}
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{$host}}"]
      endpoint = [
        {{- range $value := $config -}}
        "https://{{$value.endpoint}}",
        {{- end -}}
    ]
  {{- end }}
[plugins."io.containerd.grpc.v1.cri".registry.configs]
  {{ range $host, $config := .Values.connectivity.containerRegistries -}}
    {{ range $value := $config -}}
      {{ with $value.credentials -}}
      [plugins."io.containerd.grpc.v1.cri".registry.configs."{{$value.endpoint}}".auth]
      {{ if and .username .password -}}
      auth := {{ printf "%s:%s" .username .password | b64enc | quote }}
      {{- else if .auth -}}
      auth = {{ .auth | quote }}
      {{ else if .identitytoken -}}
      identitytoken := {{ .identitytoken  | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
