apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource.default.name" . }}-nodeclaims-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "labels.common" . | nindent 4 }}
