{{- if eq .Values.global.connectivity.cilium.ipamMode "eni" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource.default.name" . }}-cilium-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "labels.common" . | nindent 4 }}
{{- end }}
