{{/* AWS-specific cert-manager Helm values*/}}
{{/* https://github.com/giantswarm/cert-manager-app/blob/main/helm/cert-manager/values.yaml*/}}
{{- define "awsCertManagerHelmValues" }}
  dns01RecursiveNameserversOnly: true
  ingressShim:
    defaultIssuerName: letsencrypt-giantswarm
    defaultIssuerKind: ClusterIssuer
    defaultIssuerGroup: cert-manager.io
  ciliumNetworkPolicy:
    enabled: true
  route53IRSA:
    enabled: true
