{{/* AWS-specific coredns Helm values*/}}
{{/* https://github.com/giantswarm/coredns-app/blob/main/helm/coredns/values.yaml*/}}
{{- define "awsCorednsHelmValues" }}
image:
  registry: {{ include "awsContainerImageRegistry" $ }}

tolerations:
- key: ebs.csi.aws.com/agent-not-ready
  operator: Exists
- key: node.cloudprovider.kubernetes.io/uninitialized
  operator: Exists
- key: node.cluster.x-k8s.io/uninitialized
  operator: Exists
{{- end }}
