{{/* AWS-specific external-dns Helm values*/}}
{{/* https://github.com/giantswarm/external-dns-app/blob/main/helm/external-dns-app/values.yaml*/}}
{{- define "awsExternalDnsHelmValues" }}
aws:
  irsa: "true"
  batchChangeInterval: null
serviceAccount:
  annotations:
{{- $_ := set $crossplaneApp "appName" "external-dns-crossplane-resources" }}
{{- if include "cluster.app.in-release" $crossplaneApp | eq "true" }}
    eks.amazonaws.com/role-arn: "{{ .Values.global.metadata.name }}-external-dns"
{{- else }}
    eks.amazonaws.com/role-arn: "{{ .Values.global.metadata.name }}-Route53Manager-Role"
{{- end }}
extraArgs:
- "--aws-batch-change-interval=10s"
{{- end }}
