{{/* AWS-specific network-policies Helm values*/}}
{{/* https://github.com/giantswarm/network-policies-app/blob/main/helm/network-policies/values.yaml*/}}
{{- define "awsNetworkPoliciesHelmValues" }}
allowEgressToDNS:
  enabled: true
allowEgressToProxy:
  enabled: {{ $.Values.global.connectivity.proxy.enabled }}
  httpProxy: {{ $.Values.global.connectivity.proxy.httpProxy | quote }}
  httpsProxy: {{ $.Values.global.connectivity.proxy.httpsProxy | quote }}
{{- end }}
