{{- define "registry-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" $ }}-registry-configuration
data:
  registry-config.toml: {{ tpl ($.Files.Get "files/etc/containerd/config.toml") $ | b64enc | quote }}
{{- end -}}
