{{/* AWS-specific cert-manager Helm values*/}}
{{/* https://github.com/giantswarm/cert-manager-app/blob/main/helm/cert-manager/values.yaml*/}}
{{- define "awsCertManagerHelmValues" }}
{{- if eq .Values.global.connectivity.vpcMode "private" }}
dns01RecursiveNameserversOnly: true
ingressShim:
  defaultIssuerName: letsencrypt-giantswarm
  defaultIssuerKind: ClusterIssuer
  defaultIssuerGroup: cert-manager.io
ciliumNetworkPolicy:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:{{ include "aws-partition" $ }}:iam::{{ include "aws-account-id" $ }}:role/{{ include "resource.default.name" $ }}-cert-manager
giantSwarmClusterIssuer:
  acme:
    dns01:
      route53:
        enabled: true
        {{- $region := include "aws-region" . }}
        region: {{ $region }}
    http01:
      enabled: false
{{- else }}
# Default empty configuration for non-private VPC mode
{{- end }}
{{- end }}
