{{/* Default values*/}}
{{/* https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/values.yaml*/}}
{{- define "defaultCiliumHelmValues" }}
ipam:
  mode: kubernetes
k8sServiceHost: api.{{ include "resource.default.name" $ }}.{{ .Values.global.connectivity.baseDomain }}
k8sServicePort: '6443'
kubeProxyReplacement: strict
hubble:
  relay:
    enabled: true
    tolerations:
      - key: "node.cluster.x-k8s.io/uninitialized"
        operator: "Exists"
        effect: "NoSchedule"
  ui:
    tolerations:
      - key: "node.cluster.x-k8s.io/uninitialized"
        operator: "Exists"
        effect: "NoSchedule"
defaultPolicies:
  enabled: false

  tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
extraPolicies:
  allowEgressToCoreDNS:
    enabled: true
  allowEgressToProxy:
    enabled: {{ $.Values.global.connectivity.proxy.enabled }}
    httpProxy: {{ $.Values.global.connectivity.proxy.httpProxy | quote }}
    httpsProxy: {{ $.Values.global.connectivity.proxy.httpsProxy | quote }}
{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-cilium
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: cilium
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: cilium
      # used by renovate
      # repo: giantswarm/cilium-app
      version: 0.18.0-41b7fd6c24e1960206d111d27873333ca08007c9
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default-test
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 5m
  install:
    remediation:
      retries: 30
  {{- $ciliumHelmValues := (include "defaultCiliumHelmValues" .) | fromYaml -}}
  {{- $customCiliumHelmValues := $.Values.global.apps.cilium.values -}}
  {{- if $customCiliumHelmValues }}
  {{- $ciliumHelmValues = merge (deepCopy $customCiliumHelmValues) $ciliumHelmValues -}}
  {{- end }}
  {{- if $ciliumHelmValues }}
  values: {{- $ciliumHelmValues | toYaml | nindent 4 }}
  {{- end }}
  {{- if $.Values.global.apps.cilium.extraConfigs }}
  valuesFrom:
    {{- range $config := $.Values.global.apps.cilium.extraConfigs }}
    - kind: {{ $config.kind }}
      name: {{ $config.name }}
      valuesKey: values
    {{- end }}
  {{- end }}
