apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-cilium
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.metadata.description }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: cilium
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: cilium
      # used by renovate
      # repo: giantswarm/cilium-app
      version: 0.17.0
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 5m
  install:
    remediation:
      retries: 30
  # Default values
  # https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/values.yaml
  values:
    ipam:
      mode: kubernetes
    k8sServiceHost: api.{{ include "resource.default.name" $ }}.{{ .Values.baseDomain }}
    k8sServicePort: '6443'
    kubeProxyReplacement: strict
    hubble:
      relay:
        enabled: true
        tolerations:
          - key: "node.cluster.x-k8s.io/uninitialized"
            operator: "Exists"
            effect: "NoSchedule"
      ui:
        tolerations:
          - key: "node.cluster.x-k8s.io/uninitialized"
            operator: "Exists"
            effect: "NoSchedule"
    defaultPolicies:
      enabled: true

      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
    extraPolicies:
      allowEgressToCoreDNS:
        enabled: true
      allowEgressToProxy:
        enabled: {{ $.Values.connectivity.proxy.enabled }}
        httpProxy: {{ $.Values.connectivity.proxy.httpProxy | quote }}
        httpsProxy: {{ $.Values.connectivity.proxy.httpsProxy | quote }}
