{{- $_ := set $ "appName" "external-dns-crossplane-resources" }}
{{- if include "cluster.app.in-release" $ | eq "true" }}
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ printf "%s-external-dns-crossplane-resources" (include "resource.default.name" $) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  catalog: {{ include "cluster.app.catalog" $ }}
  name: external-dns-crossplane-resources
  version: {{ include "cluster.app.version" $ }}
  install:
    timeout: "10m"
  upgrade:
    timeout: "10m"
  kubeConfig:
    inCluster: true # in management cluster context
  namespace: {{ $.Release.Namespace | quote }}
  extraConfigs:
    # Created by aws-crossplane-cluster-config-operator once the cluster gets provisioned
    - kind: configMap
      name: {{ printf "%s-crossplane-config" (include "resource.default.name" $) | quote }}
      namespace: {{ $.Release.Namespace | quote }}
{{- end }}
