{{- if .Values.global.providerSpecific.irsaCrossplane }}
apiVersion: crossplane.giantswarm.io/v1
kind: IRSAClaim
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ include "resource.default.name" $ }}
spec:
  compositionRef:
    name: irsa-composition
  name: {{ include "resource.default.name" $ }}
  bucketName: {{ include "aws-account-id" . }}-g8s-{{ include "resource.default.name" $ }}-oidc-pod-identity-v3
  {{- if not (hasPrefix "cn-" (include "aws-region" .)) }}
  domain: {{ include "resource.default.name" $ }}.{{ .Values.global.connectivity.baseDomain }}
  {{- end }}
  providerConfigRef: {{ include "resource.default.name" $ }}
  region: {{ include "aws-region" . }}
  tags:
    giantswarm.io/cluster: {{ include "resource.default.name" $ }}
    giantswarm.io/installation: {{ .Values.global.managementCluster }}
    {{- if .Values.global.providerSpecific.additionalResourceTags -}}{{- toYaml .Values.global.providerSpecific.additionalResourceTags | nindent 4 }}{{- end}}
{{- end}}
