apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}-irsa-servicemonitors-user-values
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: {{ include "resource.default.name" . }}-irsa-servicemonitors
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/managed-by: {{ .Chart.Name }}
  annotations:
    app-operator.giantswarm.io/depends-on: {{ include "resource.default.name" . }}-cert-manager
spec:
  catalog: default-test
  name: irsa-servicemonitors
  {{- $_ := set $ "appName" "irsa-servicemonitors" }}
  {{- $appVersion := include "cluster.app.version" $ }}
  version: {{ $appVersion }}
  namespace: kube-system
  config:
    configMap:
      name: {{ include "resource.default.name" . }}-cluster-values
      namespace: {{ .Release.Namespace }}
  {{- if .Values.global.apps.irsaServiceMonitors.values }}
  userConfig:
    configMap:
      name: {{ include "resource.default.name" . }}-irsa-servicemonitors-user-values
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.global.apps.irsaServiceMonitors.extraConfigs }}
  extraConfigs:
  {{- range .Values.global.apps.irsaServiceMonitors.extraConfigs }}
  - kind: {{ .kind }}
    name: {{ .name }}
    namespace: {{ .namespace | default $.Release.Namespace }}
    priority: {{ .priority }}
  {{- end }}
  {{- end }}
  kubeConfig:
    inCluster: false
    secret:
      name: {{ include "resource.default.name" . }}-kubeconfig
      namespace: {{ .Release.Namespace }}
    context:
      name: {{ include "resource.default.name" . }}-admin@{{ include "resource.default.name" . }}
