{{- if include "hasKarpenterNodePool" . }}
apiVersion: v1
data:
  values: |
    karpenterNodepools:
      values:
        clusterName: {{ include "resource.default.name" $ }}
        clusterRegion: {{ include "aws-region" $ }}

        nodePools:
      {{- range $name, $value := .Values.global.nodePools | default .Values.cluster.providerIntegration.workers.defaultNodePools }}
      {{- if or (not $value.nodepoolType) (eq $value.nodepoolType "karpenter") }}
          {{ $name }}:
            rootVolumeSizeGB: {{ $value.rootVolumeSizeGB | default "8Gi" }}
            libVolumeSizeGB: {{ $value.libVolumeSizeGB | default "120Gi" }}
            logVolumeSizeGB: {{ $value.logVolumeSizeGB | default "30Gi" }}
      {{- end }}
      {{- end }}
kind: ConfigMap
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ printf "%s-karpenter-bundle" (include "resource.default.name" $) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    {{- include "labels.common" $ | nindent 4 }}
  annotations:
    app-operator.giantswarm.io/depends-on: {{ printf "%s-kyverno" (include "resource.default.name" $) | quote }}
  name: {{ printf "%s-karpenter-bundle" (include "resource.default.name" $) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  {{- $_ := set $ "appName" "karpenter-bundle" }}
  catalog: {{ include "cluster.app.catalog" $ }}
  name: karpenter-bundle
  version: {{ include "cluster.app.version" $ }}
  install:
    timeout: "10m"
  upgrade:
    timeout: "10m"
  kubeConfig:
    inCluster: true # in management cluster context
  namespace: {{ $.Release.Namespace | quote }}
  extraConfigs:
    - kind: configMap
      name: {{ printf "%s-cluster-values" (include "resource.default.name" $) | quote }}
      namespace: {{ $.Release.Namespace | quote }}
    - kind: configMap
      name: {{ printf "%s-karpenter-bundle" (include "resource.default.name" $) | quote }}
      namespace: {{ $.Release.Namespace | quote }}
{{- end }}
