{{- if include "hasKarpenterNodePool" . }}
apiVersion: v1
data:
  values: |
    karpenterNodepools:
      values:
        clusterName: {{ include "resource.default.name" $ }}
        clusterRegion: {{ include "aws-region" $ }}
        k8sVersion: {{ include "cluster.component.kubernetes.version" $ }}
        baseOS: {{ include "cluster.os.version" $ }}
        toolingVersion: {{ include "cluster.os.tooling.version" $ }}
        amiOwner: {{ if hasPrefix "cn-" (include "aws-region" .) }}306934455918{{else}}706635527432{{end}}

        nodePools:
      {{- range $name, $value := .Values.global.nodePools | default .Values.cluster.providerIntegration.workers.defaultNodePools }}
      {{- if eq $value.nodepoolType "karpenter" }}
          {{ $name }}:
            {{- (tpl ($value | toYaml | toString) $) | nindent 12 }}
            {{- with ($.Values.global.providerSpecific.nodePoolAmi | default $.Values.global.providerSpecific.ami) }}
            amiId: {{ . | quote }}
            {{- end }}
      {{- end }}
      {{- end }}
kind: ConfigMap
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ printf "%s-karpenter-bundle" (include "resource.default.name" $) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    {{- include "labels.common" $ | nindent 4 }}
  annotations:
    app-operator.giantswarm.io/depends-on: {{ printf "%s-kyverno-crds" (include "resource.default.name" $) | quote }}
  name: {{ printf "%s-karpenter-bundle" (include "resource.default.name" $) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  {{- $_ := set $ "appName" "karpenter-bundle" }}
  catalog: {{ include "cluster.app.catalog" $ }}
  name: karpenter-bundle
  version: {{ include "cluster.app.version" $ }}
  install:
    timeout: "10m"
  upgrade:
    timeout: "10m"
  kubeConfig:
    inCluster: true # in management cluster context
  namespace: {{ $.Release.Namespace | quote }}
  extraConfigs:
    - kind: configMap
      name: {{ printf "%s-cluster-values" (include "resource.default.name" $) | quote }}
      namespace: {{ $.Release.Namespace | quote }}
    - kind: configMap
      name: {{ printf "%s-karpenter-bundle" (include "resource.default.name" $) | quote }}
      namespace: {{ $.Release.Namespace | quote }}
{{- end }}
