{{- include "validation" . }}
---
{{- include "psps" . }}
{{- if not .Values.cluster.providerIntegration.resourcesApi.clusterResourceEnabled }}
---
{{- include "cluster" . }}
{{- end }}
---
{{- include "aws-cluster" . }}
---
{{- include "registry-secret" . }}
---
{{- include "control-plane" . }}
---
{{- include "machine-pools" . }}
---
{{- include "machine-health-check" . }}
