{{- include "validation" . }}
---
{{- include "psps" . }}
---
{{- include "cluster" . }}
---
{{- include "aws-cluster" . }}
---
{{- include "registry-secret" . }}
---
{{- include "control-plane" . }}
---
{{ if .Values.global.connectivity.bastion.enabled }}
{{- include "bastion" . }}
---
{{ end }}
{{- include "machine-pools" . }}
---
{{- include "machine-health-check" . }}
