{{- include "psps" . }}
---
{{- include "coredns" . }}
---
{{- include "clusterresourceset" . }}
---
{{- include "cluster" . }}
---
{{- include "aws-cluster" . }}
---
{{- include "control-plane" . }}
---
{{- include "bastion" . }}
---
{{- include "machine-pools" . }}
