{{- include "validation" . }}
---
{{- include "psps" . }}
---
{{- include "cluster" . }}
---
{{- include "aws-cluster" . }}
---
{{- include "registrySecret" }}
---
{{- include "control-plane" . }}
---
{{ if .Values.bastion.enabled }}
{{- include "bastion" . }}
---
{{ end }}
{{- include "machine-pools" . }}
