{{- include "shared.default-psps" . }}
---
{{- include "shared.coredns-adopter" . }}
---
{{- include "cluster" . }}
---
{{- include "aws-cluster" . }}
---
{{- include "bastion" . }}
---
{{- include "control-plane" . }}
---
{{- include "machine-pools" . }}
