{{- include "validation" . }}
---
{{- include "psps" . }}
---
{{- include "aws-cluster" . }}
---
{{- include "registry-secret" . }}
---
{{- include "control-plane" . }}
---
{{- include "machine-pools" . }}
---
{{- include "machine-health-check" . }}
