global:
  metadata:
    name: test-wc
    organization: "test"
  connectivity:
    baseDomain: example.com
  nodePools:
    pool0:
      maxSize: 2
      minSize: 2
      instanceTypeOverrides:
        - r6i.xlarge
        - m5.xlarge
  providerSpecific:
    region: "eu-west-1"
    awsAccountId: "1234567890"
  components:
    containerd:
      containerRegistries:
        with-auth.example.com:
        - endpoint: with-auth.example.com
          credentials:
            username: giantswarmpull
            password: abcdef
        - endpoint: quay.io

# not very nice to pass it twice like this, works for testing, will improve later
internal:
  ephemeralConfiguration:
    offlineTesting:
      renderWithoutReleaseResource: true
cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
