global:
  metadata:
    organization: "test"
  connectivity:
    containerRegistries:
      with-auth.example.com:
      - endpoint: with-auth.example.com
        credentials:
          username: giantswarmpull
          password: abcdef
      - endpoint: quay.io
baseDomain: example.com
