global:
  metadata:
    organization: "test"
  connectivity:
    baseDomain: example.com
  nodePools:
    pool0:
      maxSize: 2
      minSize: 2
      instanceTypeOverrides:
        - r6i.xlarge
        - m5.xlarge
  components:
    containerd:
      containerRegistries:
        with-auth.example.com:
        - endpoint: with-auth.example.com
          credentials:
            username: giantswarmpull
            password: abcdef
        - endpoint: quay.io
