global:
  managementCluster: test
  metadata:
    name: test-karpenter
    organization: test
  connectivity:
    baseDomain: example.com
  nodePools:
    pool0:
      type: karpenter
  providerSpecific:
    region: "eu-west-1"
  release:
    version: 29.1.0

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
