global:
  metadata:
    name: test-wc-minimal
    organization: test
    servicePriority: lowest
  nodePools:
    pool0:
      maxSize: 2
      minSize: 2
      spotInstances:
        enabled: true
        maxPrice: 1.2
baseDomain: example.com
