global:
  release:
    version: 29.1.0
  metadata:
    name: test-wc
    organization: "test"
  connectivity:
    baseDomain: example.com
  nodePools:
    pool0:
      maxSize: 2
      minSize: 2
      instanceTypeOverrides:
        - r6i.xlarge
        - m5.xlarge
  providerSpecific:
    region: "eu-west-1"
    awsAccountId: "1234567890"
    partition: "aws"
  managementCluster: test
  components:
    containerd:
      containerRegistries:
        docker.io:
          - endpoint: registry-1.docker.io
          - endpoint: giantswarm.azurecr.io
      localRegistryCache:
        enabled: true
        mirroredRegistries:
          - docker.io
        port: 32767

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
