global:
  metadata:
    name: test-wc-minimal
    organization: test
    servicePriority: lowest
  connectivity:
    baseDomain: example.com
  providerSpecific:
    region: "eu-west-1"

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
