global:
  metadata:
    name: test-wc-minimal
    organization: test
    servicePriority: lowest
  connectivity:
    baseDomain: example.com
internal:
  cgroupsv1: true
cluster:
  internal:
    advancedConfiguration:
      cgroupsv1: true
