global:
  managementCluster: test
  metadata:
    name: test-karpenter
    organization: test
  connectivity:
    baseDomain: example.com
  nodePools:
    pool0:
      maxSize: 2
      minSize: 2
      nodepoolType: karpenter
  release:
    version: v27.0.0-alpha.1
