global:
  metadata:
    name: test-wc-minimal
    organization: test
    servicePriority: lowest
  connectivity:
    baseDomain: example.com
    topology:
      mode: GiantSwarmManaged
      prefixListId: "qwe,asd"
      transitGatewayId: "123"
    vpcMode: private
  controlPlane:
    apiMode: private
  providerSpecific:
    region: "eu-west-1"
