global:
  managementCluster: test
  metadata:
    name: test-karpenter
    organization: test
  connectivity:
    baseDomain: example.com
  nodePools:
    pool1:
      type: karpenter
      additionalSecurityGroups:
        - id: sg-12345
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            volumeSize: 100Gi
            volumeType: gp3
            iops: 10000
            encrypted: true
            kmsKeyID: "1234abcd-12ab-34cd-56ef-1234567890ab"
            deleteOnTermination: true
            throughput: 125
            snapshotID: snap-0123456789
            volumeInitializationRate: 100
      consolidateAfter: 5m
      consolidationPolicy: WhenEmptyOrUnderutilized
      consolidationBudgets:
        - nodes: "20%"
        - schedule: "0 9 * * mon-fri"
          duration: "8h"
          nodes: "0"
          reasons:
            - "Drifted"
      customNodeLabels:
        - mycustomlabel=yeaaah
      customNodeTaints:
        - key: example.com/special-taint
          effect: NoSchedule
      expireAfter: 20h
      requirements:
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            - "4"
            - "8"
            - "16"
            - "32"
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      subnetTags:
        - giantswarm.io/else: "something"
  providerSpecific:
    region: "eu-west-1"
  release:
    version: 29.1.0

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
