global:
  release:
    version: v27.0.0-alpha.1
  metadata:
    name: test-wc
    organization: "test"
  connectivity:
    baseDomain: example.com
  providerSpecific:
    region: "eu-west-1"

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true

  providerIntegration:
    controlPlane:
      kubeadmConfig:
        clusterConfiguration:
          apiServer:
            serviceAccountIssuers:
              - url: https://first-issuer.example.org
              - clusterDomainPrefix: second-issuer
