global:
  managementCluster: test
  metadata:
    name: test-karpenter
    organization: test
  connectivity:
    baseDomain: example.com
  nodePools:
    pool1:
      type: karpenter
      requirements:
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
  providerSpecific:
    region: "eu-west-1"
  release:
    version: 29.1.0

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
