global:
  release:
    version: 29.1.0
  metadata:
    name: test-wc-minimal
    organization: test
    servicePriority: lowest
  connectivity:
    baseDomain: example.com
  nodePools:
    pool0:
      maxSize: 2
      minSize: 2
      spotInstances:
        enabled: true
        maxPrice: 1.2
  providerSpecific:
    region: "eu-west-1"

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
