global:
  release:
    version: v27.0.0-alpha.1
  metadata:
    name: test-mc-proxy
    organization: test
    servicePriority: lowest
  connectivity:
    baseDomain: example.com
    proxy:
      enabled: true
      httpProxy: http://proxy.mcproxy.example.com:4000
      httpsProxy: http://proxy.mcproxy.example.com:4000
  providerSpecific:
    region: "eu-west-1"
  managementCluster: test
  
cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
