name: JSON schema validation
on:
  pull_request: {}

jobs:

  validate:
    name: Validate values.schema.json with schemalint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Install schemalint
        run: |
          go install github.com/giantswarm/schemalint@latest
      - name: Run schemalint
        run: |
          schemalint verify ./helm/cluster-aws/values.schema.json --rule-set cluster-app

  values-diff:
    name: Check that values.yaml is based on values.schema.json
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Install helm-values-gen
        run: |
          go install github.com/giantswarm/helm-values-gen@latest

      - name: Run helm-values-gen
        run: >
          diff --unified ./helm/cluster-aws/values.yaml <(helm-values-gen helm/cluster-aws/values.schema.json) 
          || (echo "values.yaml is out of sync with values.schema.json. Run \`helm-values-gen helm/cluster-aws/values.schema.json -o helm/cluster-aws/values.yaml --force\` to fix this." && exit 1)
