apiVersion: v2
name: cluster-aws
description: A helm chart for creating Cluster API clusters with the AWS provider (CAPA).
version: 10.0.1
appVersion: 10.0.1
home: https://github.com/giantswarm/cluster-aws
icon: https://s.giantswarm.io/app-icons/aws/2/dark.svg
sources:
  - https://github.com/giantswarm/cluster-aws
maintainers:
  - name: Team Phoenix
    email: team-phoenix@giantswarm.io
keywords:
  - capa
  - aws
annotations:
  application.giantswarm.io/app-type: cluster
  application.giantswarm.io/team: phoenix
restrictions:
  compatibleProviders:
    - aws
dependencies:
  - repository: https://giantswarm.github.io/cluster-test-catalog
    name: cluster
    version: 8.0.1-dev.xpkim.2026-09-03.15-18-21.h23cbeed
