apiVersion: v2
name: cluster-aws
type: application
version: 8.2.0
appVersion: 8.2.0
description: A helm chart for creating Cluster API clusters with the AWS infrastructure provider (CAPA).
icon: https://s.giantswarm.io/app-icons/aws/2/dark.svg
home: https://github.com/giantswarm/cluster-aws
sources:
  - https://github.com/giantswarm/cluster-aws
annotations:
  application.giantswarm.io/app-type: cluster
  application.giantswarm.io/team: phoenix
restrictions:
  compatibleProviders:
    - aws
    - capa
dependencies:
  - name: cluster
    version: "6.3.0-80ea4db0eb47b508f4e17c5a0fc2b3d85d66620b"
    repository: https://giantswarm.github.io/cluster-test-catalog
