apiVersion: v2
name: cluster-aws
type: application
version: 7.6.0
appVersion: 7.6.0
description: A helm chart for creating Cluster API clusters with the AWS infrastructure provider (CAPA).
icon: https://s.giantswarm.io/app-icons/aws/2/dark.svg
home: https://github.com/giantswarm/cluster-aws
sources:
  - https://github.com/giantswarm/cluster-aws
annotations:
  application.giantswarm.io/app-type: cluster
  application.giantswarm.io/team: phoenix
restrictions:
  compatibleProviders:
    - aws
    - capa
dependencies:
  - name: cluster
    version: "6.0.0-932b70f1e2c8e55f3b98ee2899405c66cd63fe01"
    repository: https://giantswarm.github.io/cluster-test-catalog
  - name: cluster-shared
    version: "0.7.1"
    repository: https://giantswarm.github.io/cluster-catalog
