connectivity:
  bastion:
    enabled: true
    instanceType: t3.small
    replicas: 1
  dns:
    mode: public
  network:
    podCidr: 100.64.0.0/12
    serviceCidr: 172.31.0.0/16
  proxy: {}
  sshSsoPublicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4cvZ01fLmO9cJbWUj7sfF+NhECgy+Cl0bazSrZX7sU vault-ca@vault.operations.giantswarm.io
controlPlane:
  apiMode: public
  containerdVolumeSizeGB: 100
  etcdVolumeSizeGB: 100
  instanceType: m5.xlarge
  kubeletVolumeSizeGB: 100
  machineHealthCheck:
    enabled: true
    maxUnhealthy: 40%
    nodeStartupTimeout: 8m0s
    unhealthyNotReadyTimeout: 10m0s
    unhealthyUnknownTimeout: 10m0s
  oidc: {}
  rootVolumeSizeGB: 120
defaultMachinePools:
  def00:
    customNodeLabels:
      - label=default
    instanceType: m5.xlarge
    minSize: 3
internal:
  kubernetesVersion: 1.23.16
kubectlImage:
  name: giantswarm/kubectl
  registry: quay.io
  tag: 1.23.5
metadata: {}
network:
  availabilityZoneUsageLimit: 3
  subnets:
    - cidrBlocks:
        - availabilityZone: a
          cidr: 10.0.0.0/20
        - availabilityZone: b
          cidr: 10.0.16.0/20
        - availabilityZone: c
          cidr: 10.0.32.0/20
      isPublic: true
    - cidrBlocks:
        - availabilityZone: a
          cidr: 10.0.64.0/18
        - availabilityZone: b
          cidr: 10.0.128.0/18
        - availabilityZone: c
          cidr: 10.0.192.0/18
      isPublic: false
  topologyMode: None
  vpcCIDR: 10.0.0.0/16
  vpcEndpointMode: GiantSwarmManaged
  vpcMode: public
providerSpecific:
  awsClusterRoleIdentityName: default
  flatcarAwsAccount: "075585003325"
