clusterName: ""  # Cluster name. Defaults to chart release name
clusterDescription: "test"  # Cluster description used in metadata.
organization: ""  # Organization in which to create the cluster.
kubernetesVersion: 1.23.13
releaseVersion: 20.0.0-alpha1
baseDomain: "example.com"

aws:
  region: ""
  awsClusterRole: "default"

network:
  availabilityZoneUsageLimit: 3  # amount of AZ that should be used for the machines
  vpcCIDR: 10.0.0.0/16  # cidr range for the VPC
  serviceCIDR: 172.31.0.0/16
  podCIDR: 100.64.0.0/12

  # vpcMode defines if the VPC is created with public, internet facing resources (public subnets, NAT gateway) or not
  # Valid value: public, private
  vpcMode: public

  # apiMode defines if the Kubernetes API server load balancer should be public (internet facing) or private (internal only)
  # Valid value: public, private
  apiMode: public

  # dnsMode defines if the Route53 Hosted Zone should be public or private
  # Valid value: public, private
  dnsMode: public

  # dnsAssignAdditionalVPCs - when dnsMode is 'private', listed vpc will be assigned to the private hosted zone
  # value should be vpc id separated by comma
  # ie: "vpc-x2aeasd1d,vpc-98injA"
  dnsAssignAdditionalVPCs: ""


  # topologyMode defines the type of cross-cluster networking architecture between MCs and WCs
  # Valid values: GiantSwarmManaged, UserManaged, None
  topologyMode: None
  # transitGatewayID is the ID of the TGW to use when `mode` is set to `UserManaged`.
  transitGatewayID: ""

  subnets:
  - cidrBlock: 10.0.0.0/18
  - cidrBlock: 10.0.64.0/18
  - cidrBlock: 10.0.128.0/18

bastion:
  enabled: true
  instanceType: t3.small
  replicas: 1

controlPlane:
  instanceType: m5.xlarge
  rootVolumeSizeGB: 120
  etcdVolumeSizeGB: 100
  containerdVolumeSizeGB: 100
  kubeletVolumeSizeGB: 100

machinePools:
- name: def00  # Name of node pool.
  availabilityZones: []
  instanceType: m5.xlarge
  minSize: 3  # Number of replicas in node pool.
  maxSize: 3
  rootVolumeSizeGB: 300
  customNodeLabels:
  - label=default
  customNodeTaints: []
  # - key: ""
  #   value: ""
  #   effect: "" # Valid effects are NoSchedule, PreferNoSchedule and NoExecute.

sshSSOPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4cvZ01fLmO9cJbWUj7sfF+NhECgy+Cl0bazSrZX7sU vault-ca@vault.operations.giantswarm.io"
flatcarAWSAccount: "075585003325"

# Used to override the AMI lookup and instead use a specific image
ami: ""

oidc:
  issuerUrl: ""
  caFile: ""
  clientId: ""
  usernameClaim: ""
  groupsClaim: ""

proxy:
  enabled: false
  http_proxy: ""
  https_proxy: ""

registry:
  configure: false
  username: ""
  password: ""

# Used by `cluster-shared` library chart
includeClusterResourceSet: true
kubectlImage:
  registry: quay.io
  name: giantswarm/kubectl
  tag: 1.23.5

# Used to force-recreate resources that use a hash suffix in their name.
# To use, set this to a random string to trigger new hash values to be generated.
hashSalt: ""
